var SITE_URL = "{#SITE_URL#}";
var THEME_URL = "{$THEME_URL}";
var bLoadAjax = {#ADMIN_AJAX#|default:"true"};
var USER_LANGUAGE="{#USER_LANGUAGE#}";
var ID_CONTENT="{#FCK_BODYID#}";
var HOTKEY_OPENADMIN="{#HOTKEY_OPENADMIN#}";
var HOTKEY_OPENEDITOR="{#HOTKEY_OPENEDITOR#}";
var HOTKEY_FULLSCREEN="{#HOTKEY_FULLSCREEN#}";